version: '3.3'

services:
  nginx:
    build: './nginx'
    ports:
      - 80:80
    depends_on:
      - api_users
  api_users:
    build:
        context: './users'
        dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    volumes:
      - ./:/opt/sanic_test_users
  api_offers:
    build:
        context: './offers'
        dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    volumes:
      - ./:/opt/sanic_test_offers
    depends_on:
      - sanic_test_pg
    restart: on-failure:3
  sanic_test_pg:
    image: postgres
    environment:
      - POSTGRES_USER=${SQL_DB_USER}
      - POSTGRES_PASSWORD=${SQL_DB_PASSWORD}
      - POSTGRES_DB=${SQL_DB_NAME}
